### ISSUE TITLE
Ajaaaa! 

### ISSUE THREAD

**Issue by danmt** [piny4man/heavy-duty-camp#1]
Hermano!!! Gracias por participar... Solo una cosita, me equivoque en la presentación y me falto mencionar algo de webpack que es necesario... peeeero, por solucion temporal, reemplaza el contenido de [https://github.com/piny4man/heavy-duty-camp/blob/main/src/polyfills.ts](https://github.com/piny4man/heavy-duty-camp/blob/main/src/polyfills.ts) con esto:

```ts
/* eslint-disable @typescript-eslint/no-explicit-any */
import { Buffer } from "buffer";

(window as any).global = window;
(window as any).global.Buffer = Buffer;
(window as any).process = { env: { }}; 
```

**Comment by piny4man** [comment]
Genial! Como lo probe y tiraba la app, pense que ya estaria. Gracias @danmt

**Comment by piny4man** [comment]
@danmt listo el cambio! gracias por mencionarlo! Como voy liao durante el dia a veces paso rapido los chats y me habre pasado esta solucion :pray:

**Comment by danmt** [comment]
No te preocupes hermano mio! Fue un error de mi parte que no explique bien alguna cosita que falto.
